### PR TITLE
Convert to new Kbuild type OOT structure

### PR DESCRIPTION
**Pull request by jonasdn**
1. Use `oot-config` file instead of `-DOOT_ESTIMATOR`
 2. Use Kbuild files instead of `VPATH` and `PROG_OBJS`
 3. Set `EXTRA_CFLAGS` instead of `CFLAGS`
 4. Include `tools/make/oot.mk` instead of `Makefile`

### CODE REVIEW

**Comment by jonasdn** [comment]
Ping @knmcguire @keffklau

**Comment by knmcguire** [comment]
I guess this still needs to have the updated submodule for the crazyflie-firmware, right?

**Comment by jonasdn** [comment]
> I guess this still needs to have the updated submodule for the crazyflie-firmware, right?

Yes, this is more of a blueprint for when the submodule is bumped.

**Comment by knmcguire** [comment]
Let's close this but keep the branch in case we can still use it

**Pull request closed without merging**
